### ISSUE TITLE
no bundle install direction

### ISSUE THREAD

**Issue by raquii** [learn-co-curriculum/phase-4-rails-resources-index-show#2]
Thanks for raising this issue! Future learners thank you for your diligence. In
order to help the curriculum team address the problem, please use this template
to submit your feedback. We'll work on addressing the issue as soon as we can.

Please fill out as much of the information below as you can (it's ok if you
don't fill out every section). The more context we have, the easier it will be
to fix your issue!

_**Note**: you should only raise issues related to the contents of this lesson.
If you have questions about your code or need help troubleshooting, reach out to
an instructor/your peers._

---

## Link to Canvas

https://learning.flatironschool.com/courses/3498/assignments/128238?module_item_id=264823

## What should be changed?

The lab is missing the direction to run `bundle install`.

## Additional context
 I know that most should know to do this, but all other labs have included this direction, so it might be nice to add!

**Comment by ihollander** [comment]
Thanks for the suggestion @raquii! We added these instructions: https://github.com/learn-co-curriculum/phase-4-rails-resources-index-show/commit/7f4f22f44af9e309cebca4369731ab9c68b99b7a
